version: '3'
services:

  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4 --log-level ${LOG_LEVEL:-info} --access-logfile - --error-logfile -
    volumes:
      - .:/app/backend
      - ./static:/app/backend/static
      - ./media_volume:/app/backend/media
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:14.0-alpine
    container_name: db
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=library_db_admin
      - POSTGRES_PASSWORD=library.uz@312
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    container_name: nginx
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./static:/app/backend/static
      - ./media_volume:/app/backend/media
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:6-alpine
    container_name: redis
    volumes:
      - ./redis_data:/data/
    expose:
      - 6379

  celery:
    build: .
    container_name: celery
    command: sh -c "celery -A core worker --loglevel=info & celery -A core beat --loglevel=info"
    volumes:
      - .:/app/backend
      - ./media_volume:/app/backend/media
    depends_on:
      - redis
    env_file:
      - ./.env
